### ISSUE TITLE
Событие нажатия на маркер

### ISSUE THREAD

**Issue by bitvale** [2gis/native-sdk-android-demo#117]
Подскажите пожалуйста, а как можно отследить клик на маркер?

**Comment by lagner** [comment]
Привет.
Ключевую роль тут играет метод [getRenderedObjects](https://docs.2gis.com/ru/android/sdk/reference/1.6/ru.dgis.sdk.map.Map#nav-lvl1--getRenderedObjects). В момент клика мы вызываем этот метод и пытаемся понять какие объекты попадают в место касания. Если в списке этих объектов есть маркер, значит пользователь в него попал :)

Полное решение можно посмотреть [в этом примере](https://github.com/2gis/native-sdk-android-demo/blob/sbol-examples/app/src/main/java/ru/dgis/sdk/app/MarkersActivity.kt)
