### ISSUE TITLE
When proguard rules are enabled then the app crashes.

### ISSUE THREAD

**Issue by Aastha-dev** [2gis/native-sdk-android-demo#118]
Please add proguard rules in Read Me file

**Comment by lagner** [comment]
Why do you need it in the Readme file in the first place?
ProGuard config is part of the .aar archive and Grade has to take it into account. You don't have to do anything extra. 

Right now it contains the following lines
```
-keep class ru.dgis.sdk.** {*;}
-keep class kotlin.Unit {*;}
```
But you shouldn't rely on it since it can be changed in future releases.

**Comment by lagner** [comment]
The current problem is solved, I guess.
