### ISSUE TITLE
Отступы карты сверху и снизу

### ISSUE THREAD

**Issue by bitvale** [2gis/native-sdk-android-demo#146]
Здравствуйте, подскажите пожалуйста, в версии 2.5.2 карта не растягивается, а появляются отступы сверху и снизу. Есть настройки, которые это регулируют?

![image](https://user-images.githubusercontent.com/14936809/163389653-f2a860bd-b14c-4203-a695-1a5aa58f8fe4.png)

Проверял на ветке `sbol-example` c `ru.dgis.sdk:sdk-map:2.5.2`. 

На этой же ветке, с версией по дефолту (0.14.+) карта растягивается:

![image](https://user-images.githubusercontent.com/14936809/163389968-0d49a819-251c-4e71-aac4-02dfef35dba5.png)

Спасибо.

**Comment by lagner** [comment]
Привет.
На старой версии было ограничение по zoom. Минимальный уровень на который можно было отдалиться был 2. Сейчас zoom по умолчанию 0, мы видим всю карту, и это поведение более правильное.

Однако старый вариант можно легко вернуть. 
Если нужна карта ближе с самого начала работы, можно задать zoom c которым инициализируется карта. Это делается через [MapOptions.position](https://docs.2gis.com/ru/android/sdk/reference/2.5/ru.dgis.sdk.map.MapOptions), либо аттрибут `dgis_cameraZoom` в xml.
Если нужно чтобы камеру в принципе нельзя было отдалять так далеко, то стоит глянуть на [map.camera.zoomRestrictions ](https://docs.2gis.com/ru/android/sdk/reference/2.5/ru.dgis.sdk.map.CameraZoomRestrictions)

**Comment by bitvale** [comment]
Принял, спасибо
