### ISSUE TITLE
Marker dragging does not work

### ISSUE THREAD

**Issue by Divasik** [2gis/native-sdk-android-demo#97]
I add marker like:
```
val marker = Marker(
            MarkerOptions(
                ...
                draggable = true
            )
        ).apply {
            isDraggable = true
        }
mapObjectManager.addObject(marker)
```
But it is not dragging.
Also TouchEventsObserver added on map envokes onTap() but never onDrag* callbacks.

**Comment by lagner** [comment]
Hi @Divasik 

You are right. It was a bug we confirm it. The issue has been fixed in version 1.6.3 released a month ago. 
We should close the topic earlier but lost out attention. Sorry about that.
